export const DEFAULT_COLLECT_SCRAP_AMOUNT = 10;
export const DEFAULT_COLLECT_SCRAP_COOLDOWN_SECONDS = 3;
export const FUEL_PURCHASE_AMOUNT = 10;
export const FUEL_PURCHASE_CASH_COST = 30;
export const OIL_WELL_FUEL_AMOUNT = 1;
export const OIL_WELL_FUEL_INTERVAL_SECONDS = 4;
